# Generated by Django 3.2.15 on 2022-09-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userspokemons',
            name='pokemon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
